# Generated by Django 3.1.1 on 2020-10-16 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VehicleTypeID', models.IntegerField(default=1)),
                ('VehicleTypeDescription', models.CharField(max_length=100, verbose_name='Tipo transporte')),
            ],
            options={
                'ordering': ('VehicleTypeID',),
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VehicleID', models.CharField(default=uuid.UUID('5a703a98-13ea-4a96-8833-257058c2ebf0'), max_length=40)),
                ('ClientID', models.CharField(blank=True, max_length=40, null=True)),
                ('VehiclePatent', models.CharField(max_length=10, verbose_name='Patente del vehículo')),
                ('VehicleModel', models.CharField(max_length=100, verbose_name='Modelo')),
                ('VehicleCapacity', models.IntegerField(default=0, help_text='(ej: 5200)', verbose_name='Capacidad de carga(KG)')),
                ('VehicleAvailable', models.BooleanField(default=True, verbose_name='Vehículo disponible')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('VehicleType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transportista.vehicletype', verbose_name='Seleccione tipo de transporte')),
            ],
        ),
    ]
