# Generated by Django 3.1.1 on 2020-10-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransportInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VehicleID', models.CharField(max_length=40)),
                ('ClientID', models.CharField(max_length=40)),
                ('VehicleType', models.CharField(max_length=100, verbose_name='Tipo vehículo')),
                ('VehiclePatent', models.CharField(max_length=10, verbose_name='Patente de vehículo')),
                ('VehicleModel', models.CharField(max_length=100, verbose_name='Tipo vehículo')),
                ('VehicleCapacity', models.CharField(help_text='(ej: 5200,5)', max_length=10, verbose_name='Capacidad de carga en Kg')),
                ('VehicleAvailable', models.CharField(help_text='(ej: 25)', max_length=6, verbose_name='Vehículos disponibles')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('VehicleTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('VehicleType', models.CharField(max_length=100, verbose_name='Tipo vehículo')),
            ],
            options={
                'ordering': ('VehicleTypeID',),
            },
        ),
    ]
