# Generated by Django 3.1.1 on 2020-10-16 11:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transportista', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='VehicleAvailable',
            field=models.IntegerField(choices=[(1, 'Disponible'), (0, 'Inhabilitado')], default=1, verbose_name='Disponibilidad'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='VehicleID',
            field=models.CharField(default=uuid.UUID('d185c94f-ab6c-4eb1-9af9-853571b13f9f'), max_length=40),
        ),
    ]
