# Generated by Django 3.1.1 on 2020-10-16 20:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transportista', '0002_auto_20201016_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='VehicleID',
            field=models.CharField(default=uuid.UUID('4f50ea31-7b64-4e89-ab15-8b14d493e93a'), max_length=40),
        ),
    ]
