# Generated by Django 3.1.1 on 2020-10-16 20:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transportista', '0003_auto_20201016_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='VehicleID',
            field=models.CharField(default=uuid.UUID('9f170f12-5eb7-4e7f-9ab2-96525a863d2f'), max_length=40),
        ),
    ]
