# Generated by Django 3.1.1 on 2020-10-08 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportista', '0003_auto_20201008_1254'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VehicleTypeDescription',
            new_name='VehicleType',
        ),
        migrations.RenameField(
            model_name='vehicletype',
            old_name='VehicleType',
            new_name='VehicleTypeDescription',
        ),
    ]
