# Generated by Django 3.1.1 on 2020-10-16 20:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transportista', '0004_auto_20201016_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='VehicleID',
            field=models.CharField(default=uuid.UUID('dbc5e66b-72fe-4b75-a75e-266e3ac113b8'), max_length=40),
        ),
    ]
