# Generated by Django 3.1.1 on 2020-10-09 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportista', '0005_auto_20201009_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='VehicleCapacity',
            field=models.IntegerField(default=0, help_text='(ej: 5200,5)', verbose_name='Capacidad de carga en Kg'),
        ),
    ]
