# Generated by Django 3.1.1 on 2020-10-17 00:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transportista', '0005_auto_20201016_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='VehicleID',
            field=models.CharField(default=uuid.UUID('e0bd2d74-e9fa-437a-b496-eb236d06c19c'), max_length=40),
        ),
    ]
