# Generated by Django 3.1.1 on 2020-10-17 00:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transportista', '0006_auto_20201016_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='VehicleID',
            field=models.CharField(default=uuid.UUID('a8fd52c3-fa81-405c-b553-ffa6fa67d9e1'), max_length=40),
        ),
    ]
