# Generated by Django 3.1.1 on 2020-10-17 01:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transportista', '0007_auto_20201016_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='VehicleID',
            field=models.CharField(default=uuid.UUID('78425e1f-8c23-4cce-8b25-24b35bee1a15'), max_length=40),
        ),
    ]
