# Generated by Django 3.1.1 on 2020-10-17 01:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transportista', '0008_auto_20201016_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='VehicleID',
            field=models.CharField(default=uuid.UUID('96a18254-0352-4f2c-a75e-224da32b25a7'), max_length=40),
        ),
    ]
