# Generated by Django 3.1.1 on 2020-10-17 01:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transportista', '0009_auto_20201016_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='VehicleID',
            field=models.CharField(default=uuid.UUID('a0cf2ffb-c008-44b3-a32e-a06eac5e8a57'), max_length=40),
        ),
    ]
