# Generated by Django 3.1.1 on 2020-11-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportista', '0009_auto_20201104_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidmodel',
            name='Bidder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
