# Generated by Django 3.1.1 on 2020-10-18 03:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transportista', '0010_auto_20201016_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='VehicleID',
            field=models.CharField(default=uuid.UUID('0d957a37-619c-44d2-b387-d363b6ef3080'), max_length=40),
        ),
    ]
