# Generated by Django 3.1.1 on 2020-11-06 03:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transportista', '0010_bidmodel_bidder'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDispatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DispatchID', models.UUIDField(blank=True, default=uuid.uuid4, unique=True)),
                ('DispatchDate', models.DateField(default=datetime.date.today)),
                ('Percent', models.FloatField(default=0)),
                ('DispatchValue', models.FloatField(default=0)),
                ('DispatchWeight', models.FloatField(default=0)),
                ('Observation', models.CharField(blank=True, max_length=100, null=True)),
                ('CompanyName', models.CharField(blank=True, max_length=100, null=True)),
                ('Destination', models.CharField(blank=True, max_length=200, null=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('Status', models.IntegerField(default=0)),
                ('CarrierObservation', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ('DispatchDate',),
            },
        ),
        migrations.AlterModelOptions(
            name='auction',
            options={'ordering': ('AuctionDate',)},
        ),
        migrations.CreateModel(
            name='DispatchProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(blank=True, max_length=50, null=True)),
                ('UnitValue', models.FloatField(default=0)),
                ('Quantity', models.FloatField(default=0)),
                ('TotalValue', models.FloatField(default=0)),
                ('OrderDispatch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transportista.orderdispatch')),
            ],
        ),
    ]
