# Generated by Django 3.1.1 on 2020-10-18 04:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transportista', '0011_auto_20201018_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='VehicleID',
            field=models.CharField(default=uuid.UUID('6200949e-ab71-4b8e-85bf-d21da40e89de'), max_length=40),
        ),
    ]
