# Generated by Django 3.1.1 on 2020-11-06 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportista', '0012_orderdispatch_clientid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdispatch',
            name='Percent',
        ),
    ]
