# Generated by Django 3.1.1 on 2020-10-18 06:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transportista', '0012_auto_20201018_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='VehicleID',
            field=models.CharField(default=uuid.UUID('4273f4bf-673a-4805-880a-e3610926d668'), max_length=40),
        ),
    ]
