# Generated by Django 3.1.1 on 2020-10-29 19:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContractID', models.CharField(blank=True, max_length=40, null=True)),
                ('ClientID', models.CharField(blank=True, max_length=40, null=True)),
                ('Customername', models.CharField(blank=True, max_length=101, null=True)),
                ('CustomerDNI', models.CharField(blank=True, max_length=20, null=True)),
                ('CustomerEmail', models.CharField(blank=True, max_length=255, null=True)),
                ('ContractObservation', models.CharField(blank=True, max_length=100, null=True)),
                ('CustomerObservation', models.CharField(blank=True, max_length=100, null=True, verbose_name='ingrese observación')),
                ('StartDate', models.DateField(default=datetime.date.today)),
                ('EndDate', models.DateField(default=datetime.date.today)),
                ('IsValid', models.IntegerField(default=0)),
                ('ValidDescription', models.CharField(blank=True, max_length=30, null=True)),
                ('ContractDescription', models.CharField(blank=True, max_length=100, null=True)),
                ('CommisionValue', models.FloatField(default=0)),
                ('AdditionalValue', models.FloatField(default=0)),
                ('FineValue', models.FloatField(default=0)),
                ('Status', models.IntegerField(default=0)),
                ('StatusDescription', models.CharField(blank=True, max_length=30, null=True)),
                ('ProfileID', models.IntegerField(default=0)),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-StartDate',),
            },
        ),
    ]
