# Generated by Django 3.1.1 on 2020-10-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='AdditionalValue',
            field=models.CharField(blank=True, default='0', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='CommisionValue',
            field=models.CharField(blank=True, default='0', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='FineValue',
            field=models.CharField(blank=True, default='0', max_length=5, null=True),
        ),
    ]
