# Generated by Django 3.1.1 on 2020-10-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_auto_20201024_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='EndDate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='StartDate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
