# Generated by Django 3.1.1 on 2020-10-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_auto_20201024_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='IsValid',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='Status',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
