# Generated by Django 3.1.1 on 2020-10-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_auto_20201024_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='AdditionalValue',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='contract',
            name='CommisionValue',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='contract',
            name='FineValue',
            field=models.FloatField(default=0),
        ),
    ]
