# Generated by Django 3.1.1 on 2020-10-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0007_auto_20201024_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='IsValid',
            field=models.IntegerField(default=0),
        ),
    ]
