# Generated by Django 3.1.1 on 2020-10-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0008_auto_20201024_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ('-StartDate',)},
        ),
        migrations.AddField(
            model_name='contract',
            name='ProfileID',
            field=models.IntegerField(default=0),
        ),
    ]
