# Generated by Django 3.1.1 on 2020-10-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0009_auto_20201025_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='CustomerObservation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ingrese observación'),
        ),
    ]
