# Generated by Django 3.1.1 on 2020-10-19 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productor', '0002_auto_20201018_1529'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderID', models.CharField(default=uuid.UUID('635443c7-c53f-4b28-9580-b9f992bd1e28'), max_length=40)),
                ('ClientID', models.CharField(blank=True, max_length=40, null=True)),
                ('OrderDate', models.DateField(auto_now_add=True)),
                ('OrderDiscount', models.FloatField(default=0, verbose_name='¿Tiene descuento?')),
            ],
            options={
                'verbose_name': 'Orden de compra',
                'verbose_name_plural': 'Ordenes de compras',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PaymentCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ConditionID', models.IntegerField(default=1)),
                ('ConditionDescription', models.CharField(max_length=25, verbose_name='Condición de pago')),
            ],
            options={
                'ordering': ('ConditionID',),
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderDetailID', models.CharField(default=uuid.UUID('05944a6d-8c8e-42bb-9671-2a65b823f614'), max_length=40)),
                ('Quantity', models.FloatField(default=0, verbose_name='Cantidad de productos (medido en KG)')),
                ('Order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cexterno.order')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productor.producto', verbose_name='Seleccione producto')),
            ],
            options={
                'verbose_name': 'Detalle de orden',
                'verbose_name_plural': 'Detalles de ordenes',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='PaymentCondition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cexterno.paymentcondition', verbose_name='Condiciones de pago'),
        ),
        migrations.AddField(
            model_name='order',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
