# Generated by Django 3.1.1 on 2020-10-19 02:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cexterno', '0002_auto_20201018_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Observation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='order',
            name='OrderDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='OrderID',
            field=models.CharField(default=uuid.UUID('e61e20ef-47e4-43f4-a772-763403134859'), max_length=40),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='OrderDetailID',
            field=models.CharField(default=uuid.UUID('d5293d51-d42c-4740-aa74-e43763d2d2e2'), max_length=40),
        ),
    ]
