# Generated by Django 3.1.1 on 2020-10-19 03:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cexterno', '0003_auto_20201018_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='OrderID',
            field=models.CharField(default=uuid.UUID('a88fb8b5-72f9-4394-b0ba-b48377f0d042'), max_length=40),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='OrderDetailID',
            field=models.CharField(default=uuid.UUID('6906f258-5ba4-4409-a910-8564de36f975'), max_length=40),
        ),
    ]
