# Generated by Django 3.1.1 on 2020-10-19 05:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cexterno', '0004_auto_20201019_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='OrderID',
            field=models.CharField(default=uuid.UUID('6f905bba-a625-4b7a-bfdc-94ce106d3820'), max_length=40),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='OrderDetailID',
            field=models.CharField(default=uuid.UUID('bbcdf040-a086-482c-875c-4a39fbf9b995'), max_length=40),
        ),
    ]
