# Generated by Django 3.1.1 on 2020-10-15 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductID', models.CharField(default=uuid.UUID('54ee2c3c-a102-4dc7-ba64-f97e123c99cf'), max_length=40)),
                ('ClientID', models.CharField(blank=True, max_length=40, null=True)),
                ('ProductName', models.CharField(max_length=50, verbose_name='Nombre producto')),
                ('Observation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observación')),
                ('ProductValue', models.FloatField(default=0, verbose_name='Valor del producto')),
                ('ProductQuantity', models.FloatField(default=0, verbose_name='Cantidad de productos (medido en KG)')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ('id',),
            },
        ),
    ]
