# Generated by Django 3.1.1 on 2020-10-30 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryID', models.IntegerField(default=1)),
                ('CategoryName', models.CharField(max_length=25, verbose_name='Categoría de producto')),
            ],
            options={
                'ordering': ('CategoryID',),
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductID', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('ClientID', models.CharField(blank=True, max_length=40, null=True)),
                ('ProductName', models.CharField(max_length=50, verbose_name='Nombre producto')),
                ('ProductValue', models.FloatField(default=0, verbose_name='Valor del producto')),
                ('ProductQuantity', models.FloatField(default=0, verbose_name='Cantidad de productos (medido en KG)')),
                ('Observation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observación')),
                ('Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productor.category', verbose_name='Seleccione categoría de producto')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ('id',),
            },
        ),
    ]
