# Generated by Django 3.1.1 on 2020-10-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('CategoryID',)},
        ),
        migrations.AlterField(
            model_name='category',
            name='CategoryName',
            field=models.CharField(max_length=25, verbose_name='Categoría de producto'),
        ),
    ]
