# Generated by Django 3.1.1 on 2020-10-15 19:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0002_auto_20201015_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ProductID',
            field=models.CharField(default=uuid.UUID('ef2b039f-0b04-442c-9f7a-093f689245fb'), max_length=40),
        ),
    ]
