# Generated by Django 3.1.1 on 2020-10-16 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0003_auto_20201015_1634'),
        ('productor', '0002_auto_20201016_0818'),
    ]

    operations = [
    ]
