# Generated by Django 3.1.1 on 2020-10-16 20:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0004_merge_20201016_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ProductID',
            field=models.CharField(default=uuid.UUID('e0ea8148-6b99-4621-a35e-af1b486586d7'), max_length=40),
        ),
    ]
