# Generated by Django 3.1.1 on 2020-10-16 20:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0005_auto_20201016_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ProductID',
            field=models.CharField(default=uuid.UUID('2939d534-3f79-4278-8714-53bdefeeef8d'), max_length=40),
        ),
    ]
