# Generated by Django 3.1.1 on 2020-10-16 20:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0006_auto_20201016_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ProductID',
            field=models.CharField(default=uuid.UUID('59c83ff5-456e-40a3-8e96-4e21e4026849'), max_length=40),
        ),
    ]
