# Generated by Django 3.1.1 on 2020-10-17 00:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0007_auto_20201016_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ProductID',
            field=models.CharField(default=uuid.UUID('fb6a6be0-eedd-462f-a4a2-0d161f3714e2'), max_length=40),
        ),
    ]
