# Generated by Django 3.1.1 on 2020-10-17 00:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0008_auto_20201016_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ProductID',
            field=models.CharField(default=uuid.UUID('849ce2b6-4f73-4d2b-a7ee-f88231cf9c8d'), max_length=40),
        ),
    ]
