# Generated by Django 3.1.1 on 2020-10-17 01:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0010_auto_20201016_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ProductID',
            field=models.CharField(default=uuid.UUID('feddef10-1e07-4b7c-b2c0-4fc0eeae1d93'), max_length=40),
        ),
    ]
