# Generated by Django 3.1.1 on 2020-10-17 01:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0011_auto_20201016_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ProductID',
            field=models.CharField(default=uuid.UUID('90eb4093-f79d-4a80-b7b8-bef76a148ca7'), max_length=40),
        ),
    ]
