# Generated by Django 3.1.1 on 2020-10-18 03:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0012_auto_20201016_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ProductID',
            field=models.CharField(default=uuid.UUID('1eb1e5a4-f561-4061-a66a-a3c4b03b5647'), max_length=40),
        ),
    ]
