# Generated by Django 3.1.1 on 2020-10-18 04:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0013_auto_20201018_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ProductID',
            field=models.CharField(default=uuid.UUID('1c807b57-592f-4f8b-bed7-b01d73ac11a0'), max_length=40),
        ),
    ]
