# Generated by Django 3.1.1 on 2020-10-18 06:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0014_auto_20201018_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ProductID',
            field=models.CharField(default=uuid.UUID('ea70b640-9f35-4fa6-bd0b-90d11796b48c'), max_length=40),
        ),
    ]
