# Generated by Django 3.1.1 on 2020-10-06 23:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('CityID', models.AutoField(primary_key=True, serialize=False)),
                ('CityName', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('CityID',),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('CountryID', models.AutoField(primary_key=True, serialize=False)),
                ('CountryName', models.CharField(max_length=100)),
                ('CountryPrefix', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'ordering': ('CountryID',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('ProfileID', models.AutoField(primary_key=True, serialize=False)),
                ('ProfileName', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('ProfileID',),
            },
        ),
        migrations.CreateModel(
            name='ComercialInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClientID', models.CharField(max_length=40)),
                ('ComercialID', models.CharField(max_length=40)),
                ('CompanyName', models.CharField(max_length=100, verbose_name='Razón social')),
                ('FantasyName', models.CharField(max_length=100, verbose_name='Nombre de fantasía')),
                ('ComercialBusiness', models.CharField(max_length=100, verbose_name='Giro comercial')),
                ('Email', models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator('^[+a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,4}$')], verbose_name='Email comercial')),
                ('ComercialDNI', models.CharField(help_text='(ej: 12345678-9)', max_length=20, verbose_name='DNI comercial')),
                ('Address', models.CharField(max_length=100, verbose_name='Dirección comercial')),
                ('PhoneNumber', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('City', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city', verbose_name='Seleccione ciudad')),
                ('Country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country', verbose_name='Seleccione país')),
                ('User', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='Country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country'),
        ),
    ]
