# Generated by Django 3.1.1 on 2020-10-16 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='comercialinfo',
            name='City',
        ),
        migrations.RemoveField(
            model_name='comercialinfo',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='comercialinfo',
            name='User',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='ComercialInfo',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
